// <auto-generated />
using Eshop.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eshop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum sudo lomen sili imeni anto destre umeni quarto luremo lumeni",
                            Image = "https://dummyimage.com/600x400/ffffff/000000",
                            Price = 9.99m,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum sudo lomen sili imeni anto destre umeni quarto luremo lumeni",
                            Image = "https://dummyimage.com/600x400/ffffff/000000",
                            Price = 9.99m,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum sudo lomen sili imeni anto destre umeni quarto luremo lumeni",
                            Image = "https://dummyimage.com/600x400/ffffff/000000",
                            Price = 9.99m,
                            Title = "Book 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
