// <auto-generated />
using System;
using Ecommerce.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ecommerce.Shared.Books.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BiographyText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiographyText = "No author",
                            Image = "",
                            Name = "No author",
                            Url = "no-author"
                        },
                        new
                        {
                            Id = 2,
                            BiographyText = "Joanne Rowling, better known by her pen name J.K. Rowling, is a British author, best known for writing the Harry Potter series.",
                            Image = "",
                            Name = "J.K. Rowling",
                            Url = "joanne-rowling"
                        },
                        new
                        {
                            Id = 3,
                            BiographyText = "George Raymond Richard Martin, often referred to as GRRM, is an American novelist and short story writer, known for his series A Song of Ice and Fire.",
                            Image = "",
                            Name = "George R.R. Martin",
                            Url = "george-raymond-richard-martin"
                        },
                        new
                        {
                            Id = 4,
                            BiographyText = "John Ronald Reuel Tolkien was an English writer, poet, and university professor. He is best known as the author of the classic high-fantasy works The Hobbit, The Lord of the Rings, and The Silmarillion.",
                            Image = "",
                            Name = "J.R.R. Tolkien",
                            Url = "john-ronald-reuel-tolkien"
                        },
                        new
                        {
                            Id = 5,
                            BiographyText = "Agatha Christie was an English writer known for her detective novels, particularly those revolving around her fictional detectives Hercule Poirot and Miss Marple.",
                            Image = "",
                            Name = "Agatha Christie",
                            Url = "agatha-christie"
                        },
                        new
                        {
                            Id = 6,
                            BiographyText = "Stephen King is an American author of horror, supernatural fiction, suspense, crime, science-fiction, and fantasy novels.",
                            Image = "",
                            Name = "Stephen King",
                            Url = "stephen-king"
                        },
                        new
                        {
                            Id = 7,
                            BiographyText = "Renowned science fiction writer",
                            Image = "",
                            Name = "Isaac Asimov",
                            Url = "issac-asimov"
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CopiesInStore")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Featured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesOrder")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            CategoryId = 2,
                            CopiesInStore = 150,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8282),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/h/hra-o-truny-9788025722824.jpg",
                            Deleted = false,
                            Description = "Winter is coming. A classic world that best describes George R. R. Martin's epic saga A Song of Ice and Fire. The kingdoms of Westeros have a long summer, which must be followed by a harsh winter. But before that, and before the Others return, the game of thrones is being played out, and there are far fewer contenders than contenders. Perhaps the only one who doesn't want the Iron Throne is Lord Eddard Stark, guardian of the north. Therefore, he must become the mover of events that will change everything.",
                            Featured = true,
                            Isbn = "978-80-257-2282-4",
                            PageCount = 694,
                            ReleaseDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 3,
                            SeriesOrder = 1,
                            ShortDescription = " The kingdoms of Westeros have a long summer, which must be followed by a harsh winter. But before that, and before the Others return, the game of thrones is being played out, and there are far fewer contenders than contenders.",
                            Title = "Game of Thrones",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            CategoryId = 2,
                            CopiesInStore = 120,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8353),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/kniha/stret-kralu-39500927",
                            Deleted = false,
                            Description = "The Seven Kingdoms are divided by revolt and blood feud, and winter approaches like an angry beast. Beyond the Wall, the armies of the Night's Watch are massing for an assault on the kingdom of the dead. The young, the brave, and the foolish, all compete for the throne.",
                            Featured = false,
                            Isbn = "978-0553579901",
                            PageCount = 768,
                            ReleaseDate = new DateTime(1998, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 3,
                            SeriesOrder = 2,
                            ShortDescription = "Winter approaches and armies gather. The battle for the throne continues...",
                            Title = "A Clash of Kings",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            CopiesInStore = 100,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8361),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/b/boure-mecu-9788025724187_17.jpg",
                            Deleted = false,
                            Description = "The Seven Kingdoms are divided by revolt and blood feud, and winter approaches like an angry beast. Beyond the Wall, the armies of the Night's Watch are massing for an assault on the kingdom of the dead. The young, the brave, and the foolish, all compete for the throne.",
                            Featured = true,
                            Isbn = "978-0553573428",
                            PageCount = 992,
                            ReleaseDate = new DateTime(2000, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 3,
                            SeriesOrder = 3,
                            ShortDescription = "Winter approaches and armies gather. The battle for the throne continues...",
                            Title = "A Storm of Swords",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 2,
                            CopiesInStore = 130,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8367),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/p/pan-prstenu-spolecenstvo-prstenu-ilustrovane-vydani-9788072038299_26.jpg",
                            Deleted = false,
                            Description = "The first part of J.R.R. Tolkien's epic masterpiece The Lord of the Rings. The story begins with the hobbit Frodo Baggins inheriting the Ring from his uncle Bilbo. Together with his fellowship, he embarks on a dangerous journey to destroy the Ring and defeat the Dark Lord Sauron.",
                            Featured = false,
                            Isbn = "978-0618640157",
                            PageCount = 432,
                            ReleaseDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 4,
                            SeriesOrder = 1,
                            ShortDescription = "The journey to destroy the One Ring begins...",
                            Title = "The Fellowship of the Ring",
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            CategoryId = 3,
                            CopiesInStore = 110,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8374),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/n/nadace-9788025728802_4.jpg",
                            Deleted = false,
                            Description = "Foundation is the first novel in Isaac Asimov's Foundation series. The story follows mathematician Hari Seldon, who predicts the fall of the Galactic Empire. To shorten the impending dark age, he establishes a plan to preserve knowledge and guide humanity's future.",
                            Featured = false,
                            Isbn = "978-0553293357",
                            PageCount = 244,
                            ReleaseDate = new DateTime(1951, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 7,
                            SeriesOrder = 1,
                            ShortDescription = "A tale of the decline and revival of a galactic empire...",
                            Title = "Foundation",
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            CategoryId = 2,
                            CopiesInStore = 125,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8382),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/p/pan-prstenu-dve-veze-9788072038305_20.jpg",
                            Deleted = false,
                            Description = "The second part of J.R.R. Tolkien's epic masterpiece The Lord of the Rings. Frodo and the fellowship face new challenges as they continue their quest to destroy the Ring, while war threatens to engulf Middle-earth.",
                            Featured = false,
                            Isbn = "978-0618260262",
                            PageCount = 352,
                            ReleaseDate = new DateTime(1954, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 4,
                            SeriesOrder = 2,
                            ShortDescription = "The quest continues amidst growing darkness...",
                            Title = "The Two Towers",
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CategoryId = 3,
                            CopiesInStore = 105,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8389),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/n/nadace-a-rise-9788075539182-17.",
                            Deleted = false,
                            Description = "Foundation and Empire is the second book in Isaac Asimov's Foundation series. The story follows the rise of a new empire and a confrontation between two powerful forces: the Foundation and the Empire.",
                            Featured = true,
                            Isbn = "978-0553293371",
                            PageCount = 272,
                            ReleaseDate = new DateTime(1952, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 7,
                            SeriesOrder = 2,
                            ShortDescription = "The struggle for dominance in a galaxy at the edge of chaos...",
                            Title = "Foundation and Empire",
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            CategoryId = 5,
                            CopiesInStore = 90,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8396),
                            DefaultImageUrl = "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/v/vrazda-v-orient-expresu-9788024277349_10.jpg",
                            Deleted = false,
                            Description = "Hercule Poirot investigates a murder on the luxurious Orient Express train. A classic murder mystery novel by Agatha Christie.",
                            Featured = false,
                            Isbn = "978-0062693662",
                            PageCount = 256,
                            ReleaseDate = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 5,
                            SeriesOrder = 1,
                            ShortDescription = "A murder mystery on a train...",
                            Title = "Murder on the Orient Express",
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            CategoryId = 4,
                            CopiesInStore = 85,
                            DateAdded = new DateTime(2024, 1, 9, 23, 14, 56, 542, DateTimeKind.Local).AddTicks(8402),
                            DefaultImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/The_Stand_%281978%29_front_cover%2C_first_edition.png/220px-The_Stand_%281978%29_front_cover%2C_first_edition.png",
                            Deleted = false,
                            Description = "A post-apocalyptic horror novel by Stephen King. After a deadly plague kills most of the world's population, survivors are drawn to two charismatic leaders, leading to a final stand between good and evil.",
                            Featured = true,
                            Isbn = "978-0307743688",
                            PageCount = 1153,
                            ReleaseDate = new DateTime(1978, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeriesId = 6,
                            SeriesOrder = 1,
                            ShortDescription = "The battle between good and evil after a pandemic...",
                            Title = "The Stand",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.BookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BookTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paperback"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hardcover"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ebook"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audiobook"
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.BookVariant", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BookTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "BookTypeId");

                    b.HasIndex("BookTypeId");

                    b.ToTable("BookVariants");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 30.99m,
                            Price = 20.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 1,
                            BookTypeId = 2,
                            Deleted = false,
                            OriginalPrice = 20.99m,
                            Price = 15.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 1,
                            BookTypeId = 4,
                            Deleted = false,
                            OriginalPrice = 20.99m,
                            Price = 10.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 2,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 30.99m,
                            Price = 25.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 2,
                            BookTypeId = 2,
                            Deleted = false,
                            OriginalPrice = 25.99m,
                            Price = 20.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 3,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 35.99m,
                            Price = 30.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 3,
                            BookTypeId = 3,
                            Deleted = false,
                            OriginalPrice = 20.99m,
                            Price = 15.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 4,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 28.99m,
                            Price = 22.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 4,
                            BookTypeId = 3,
                            Deleted = false,
                            OriginalPrice = 23.99m,
                            Price = 17.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 5,
                            BookTypeId = 2,
                            Deleted = false,
                            OriginalPrice = 24.99m,
                            Price = 19.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 5,
                            BookTypeId = 4,
                            Deleted = false,
                            OriginalPrice = 19.99m,
                            Price = 14.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 8,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 19.99m,
                            Price = 14.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 8,
                            BookTypeId = 2,
                            Deleted = false,
                            OriginalPrice = 24.99m,
                            Price = 19.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 9,
                            BookTypeId = 1,
                            Deleted = false,
                            OriginalPrice = 25.99m,
                            Price = 20.99m,
                            Visible = true
                        },
                        new
                        {
                            BookId = 9,
                            BookTypeId = 3,
                            Deleted = false,
                            OriginalPrice = 20.99m,
                            Price = 15.99m,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Default",
                            Url = "default",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Fantasy",
                            Url = "fantasy",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Sci-fi",
                            Url = "scifi",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "Horror",
                            Url = "horror",
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "Detective",
                            Url = "detective",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Books that are not part of any series",
                            Name = "Stand alone",
                            Url = "stand-alone"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The magical adventures of Harry Potter",
                            Name = "Harry Potter",
                            Url = "harry-potter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Epic fantasy series by George R.R. Martin",
                            Name = "A Song of Ice and Fire",
                            Url = "a-song-of-ice-and-fire"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Classic high-fantasy series by J.R.R. Tolkien",
                            Name = "The Lord of the Rings",
                            Url = "the-lord-of-the-rings"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Detective series by Agatha Christie",
                            Name = "Hercule Poirot",
                            Url = "hercule-poirot"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Horror novels by Stephen King",
                            Name = "Stephen King Horror Novels",
                            Url = "stephen-king-horror-novels"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sci-fi series by Isaac Asimov",
                            Name = "Foundation",
                            Url = "foundation"
                        });
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Book", b =>
                {
                    b.HasOne("Ecommerce.Shared.Books.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Shared.Books.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Shared.Books.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.BookVariant", b =>
                {
                    b.HasOne("Ecommerce.Shared.Books.Book", "Book")
                        .WithMany("Variants")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Shared.Books.BookType", "BookType")
                        .WithMany()
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookType");
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Image", b =>
                {
                    b.HasOne("Ecommerce.Shared.Books.Book", null)
                        .WithMany("Images")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("Ecommerce.Shared.Books.Book", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
